### ISSUE TITLE
2.1.0 Release Roadmap

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10339]
Hi everyone, we are delighted to announce a new release 2.1.0 in the upcoming weeks.

@dmlc/xgboost-committer 

If you have specific items that you want to include in the upcoming release, please share them in the comment below. Let's ensure that

- Each item has an associated ticket
- Major design/refactoring is associated with an RFC before committing the code
- Blocking issue must be marked as blocking
- Breaking change must be marked as breaking

The 2.1.0 release will exclude the R interface due to https://github.com/dmlc/xgboost/issues/9810 . We will update the R package once the new interface is complete. Stay tuned.

# backport
- [x] https://github.com/dmlc/xgboost/pull/10322
- [x] https://github.com/dmlc/xgboost/pull/10374
- [x] https://github.com/dmlc/xgboost/pull/10385
- [x] https://github.com/dmlc/xgboost/pull/10408
- [x] #10404
- [x] #10419 
- [x] #10418
- [x] #10414 
- [x] #10435
- [x] https://github.com/dmlc/xgboost/pull/10433
- [x] https://github.com/dmlc/xgboost/pull/10399
- [x] https://github.com/dmlc/xgboost/pull/10440
- [x] #10449
- [x] https://github.com/dmlc/xgboost/pull/10447

**Comment by trivialfis** [comment]
@hcho3 Please help upload the jvm packages to maven. I have submitted updates for PyPI.

**Comment by hcho3** [comment]
@trivialfis I submitted the 2.1.0 release to Maven Central.
