### ISSUE TITLE
2.1.1 Patch Release

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10575]
- [x] https://github.com/dmlc/xgboost/pull/10480
- [x] https://github.com/dmlc/xgboost/pull/10476
- [x] https://github.com/dmlc/xgboost/pull/10503
- [x] https://github.com/dmlc/xgboost/pull/10539
- [x] https://github.com/dmlc/xgboost/pull/10559
- [x] https://github.com/dmlc/xgboost/pull/10572
- [x] #10603 
- [x] https://github.com/dmlc/xgboost/pull/10623
- [x] https://github.com/dmlc/xgboost/pull/10632
- [x] Update document branch.
- [x] #10624
- [x] #10633
- [x] #10574
- [x] #10643
- [x] #10642

**Comment by trivialfis** [comment]
The dask interface prediction might run into hang when the booster is large, will wait for the debugging result.

**Comment by hcho3** [comment]
@trivialfis I think we are ready to make the 2.1.1 release. Let me handle the uploading of the Python wheels this time so that I can iron out any issues with `xgboost-cpu`.

**Comment by jakirkham** [comment]
Thanks Jiaming and Hyunsu! 🙏

Did a pass through the patches in conda-forge

Think this one maybe we can just drop? Would be good to double check:

* https://github.com/conda-forge/xgboost-feedstock/issues/175

Also think we might be able to upstream two. Have started PRs for them. Would be interested to hear your feedback 🙂

* https://github.com/dmlc/xgboost/pull/10643
* https://github.com/dmlc/xgboost/pull/10642

If we are able to close those out, think we can drop all the patches in conda-forge, which would be really nice for our update process 😄

Not to mention in XGBoost 2.1.0, we switched to using [the source tarball made at release time]( https://github.com/dmlc/xgboost/commit/4caca2947df22fa76af27bbaad379aafe9f6c51d#diff-2ac152fd163224cdb5c3aa624040df4dca8b1860ac4bde19bafc23dbb432d172R186-R212 ). This should help the conda-forge autoupdate bot to start submitting PRs to the feedstock 🎉

**Comment by hcho3** [comment]
The 2.1.1 release is now available on PyPI and Maven Central.
