### ISSUE TITLE
2.1.2 Patch Release

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10885]
- [x] https://github.com/dmlc/xgboost/pull/10880
- [x] https://github.com/dmlc/xgboost/pull/10767
- [x] #10872
- [x] #10755
- [x] #10719
- [x] #10721
- [x] #10818
- [x] https://github.com/dmlc/xgboost/pull/10527
- [x] https://github.com/dmlc/xgboost/pull/10906
- [x] https://github.com/dmlc/xgboost/pull/10908

**Comment by hcho3** [comment]
Blocking issue: #10879

**Comment by trivialfis** [comment]
@hcho3 Does it affect the 2.1 branch?

**Comment by hcho3** [comment]
Is the JVM rewrite part of 2.1.2 ?

**Comment by trivialfis** [comment]
No. It's a patch release for bug fixes.

**Comment by trivialfis** [comment]
Thank you for the reminder, added to the list.

**Comment by trivialfis** [comment]
@hcho3 Could you please help take a look into the new release script, I'm running into:
```
twine check /home/jiamingy/workspace/xgboost_dev/xgboost/python-package/dist/xgboost-2.1.2.tar.gz
ERROR    InvalidDistribution: Cannot find file (or expand pattern):                                                       '/home/jiamingy/workspace/xgboost_dev/xgboost/python-package/dist/xgboost-2.1.2.tar.gz' 
```
when doing twine check.

In addition, this [line](https://github.com/dmlc/xgboost/blob/c06994b2fbad93ff7377549b4ae9d27e16b45188/dev/release-artifacts.py#L199) is not needed, the url uses the full branch name.

**Comment by trivialfis** [comment]
NVM, I think I didn't update the tag correctly.

**Comment by trivialfis** [comment]
Done.
