### ISSUE TITLE
2.1.3 Patch release.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#10992]
This will be a path release for some bug fixes for distributed environments.

- [ ] ~https://github.com/dmlc/xgboost/pull/10973~ (won't backport, too many conflicts)
- [x] https://github.com/dmlc/xgboost/pull/10984
- [x] https://github.com/dmlc/xgboost/pull/10998
- [x] https://github.com/dmlc/xgboost/pull/11014

**Comment by trivialfis** [comment]
@hcho3 I have uploaded all the Python packages, could you please help upload the jvm packages when you are available?

**Comment by trivialfis** [comment]
@hcho3 Did you get a chance to look into this?

**Comment by hcho3** [comment]
Working on it now

**Comment by hcho3** [comment]
2.1.3 is now available on Maven Central.
