### ISSUE TITLE
Roadmap: MinGW build support (32/64-bit)

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#3436]
There has been a report (e.g. #2958) reporting compilation failure with MinGW. This issue is intended to keep track of progress with regards to MinGW build support.

Currently, Windows CI tests (on AppVeyor) build XGBoost with MSYS-MinGW. Feel free to report any variant of MinGW that fails to build XGBoost.

- [x] MSYS-MinGW (part of CI)
- [x] RTools (part of CI)
- [ ] [m2w64-toolchain](https://anaconda.org/msys2/m2w64-toolchain)
- [ ] [MinGW upstream](https://sourceforge.net/projects/mingw-w64/)

**Comment by hcho3** [comment]
Relevant section of AppVeyor build tests for MinGW:
https://github.com/dmlc/xgboost/blob/master/appveyor.yml#L36
https://github.com/dmlc/xgboost/blob/master/appveyor.yml#L67

**Comment by hcho3** [comment]
@KOLANICH Thanks a lot. Sorry again for massively closing issues. From now on, we'll try to keep the number of open issues small. All MinGW-related issues and works will be posted in this thread, so as to keep track of overall progress in MinGW support.

**Comment by KOLANICH** [comment]
It is impossible to find out whichncompiler is used solely withnpreprocessor. So I have implemented a CMake solution and have thrown away old duct tape. Now if the definition is needed is determined by presence of the function. 
https://github.com/dmlc/dmlc-core/pull/432

If you dislike my solution, fill free to add commits above it.

**Comment by hcho3** [comment]
Closing this for now since dmlc/dmlc-core#432 has been merged.
