### ISSUE TITLE
[ANNOUCEMENT] 0.81 release planned on November 1, 2018

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#3744]
We will release version 0.81 on October 15, 2018.

Blocking issues / PRs
- [x] #3523: colsample_bytree seemingly not random
- [x] #3543: Multi-threading not working properly with version 0.71.2
- [x] #3579: hist + learning_rate decay memory usage
- [x] #3643: Lanuch function for unifying CPU and GPU code
- [x] #3738: Multi-GPU support in GPUPredictor
- [x] #3746: Binary wheels are broken on CPU-only containers
- [x] #3750: For training data with group, empty RDD partition threw exception
- [x] #3758:  fix issue when spark job execution thread cannot return before we execute first()
- [x] #3808: fix the early stopping feature in XGBoost4J
- [x] #3809: benchmark/benchmark_tree.py failed
- [x] #3816: Upgrade Scala to 2.11.12 to address security vulnerability
- [x] #3840: `tree_method=approx` invokes the wrong tree updater class

**Comment by hcho3** [comment]
@RAMitchell @trivialfis @canonizer Do we want to merge #3643 and #3738 before the 0.81 release? The release determines what `pip install xgboost` will install.

**Comment by RAMitchell** [comment]
Yes I think we can merge #3643 now and #3738 should be easily doable before October 15.

**Comment by hcho3** [comment]
Adding #3746 as blocking issue.

**Comment by hcho3** [comment]
Pushing back the release date to November 1 due to blocking issues.

**Comment by CodingCat** [comment]
for #3543 and #3579  do we have active PR?

**Comment by hcho3** [comment]
Not yet. Still investigating.

**Comment by hcho3** [comment]
#3579 is addressed by #3803.

**Comment by trivialfis** [comment]
@hcho3 Can we add #3809 to blocking?  I really worry about multi-gpu.

**Comment by hcho3** [comment]
@trivialfis Done

**Comment by hcho3** [comment]
One thing I want to get done is the proper CI for CUDA 10.0: 1) a new build worker with CUDA toolkit 10.0 will run unit tests and 2) wheels built with CUDA 8.0 would be checked so that it installs on machines with CUDA 10.0.

**Comment by maedabr** [comment]
Hi @hcho3 , do you know if this version will be release today?

**Comment by hcho3** [comment]
Unfortunately, the release is being delayed by #3840. I'm working on it.

**Comment by hcho3** [comment]
I will go ahead and draft the release note for the new version.

**Comment by hcho3** [comment]
I think #3856 is well tested and should be part of the 0.81 release. You will see a PR for new release by end of today (Pacific Time).
