### ISSUE TITLE
[EPIC] Allow failed worker retry in distributed training

### ISSUE THREAD

**Issue by chenqin** [dmlc/xgboost#4753]
Fault recovery in native distributed XGB training (not xgb-spark) have been broken for more than a year. Community have seen various of issue like this https://github.com/dmlc/rabit/issues/63

- [x] expose flag to opt-in detailed log in rabit
- [x] support bootstrap cache in rabit , expose flag to opt-in rabit bootstrap cache
[design doc.pdf](https://github.com/dmlc/xgboost/files/3482936/Rabit.bootstrap.operations.support.pdf)
PR candidate: https://github.com/dmlc/rabit/pull/98
- [x] patch native xgb code base and support worker retry
pr https://github.com/dmlc/rabit/pull/102 cleanup rabit api
pr https://github.com/dmlc/xgboost/pull/4808 patch xgb worker
pr https://github.com/dmlc/rabit/pull/106 unittest rabit, cleanup make file
- [ ] patch xgb-spark code base and support task retry
   design https://github.com/dmlc/xgboost/issues/4831
    -  [x] surface configuration to jvm layer https://github.com/dmlc/xgboost/issues/4861 pr https://github.com/dmlc/xgboost/pull/4966
   -  [x] short circuit, timeout rabit https://github.com/dmlc/rabit/issues/105
   -   [ ] enable failed foreachparition spark task retry and disable spark checkpoint if user opt-in with configuration "rabit_bootstrap_cache=1"

tracking backlogs work from merged prs 
- [ ] move histogram init before loadcheckpoint. https://github.com/dmlc/xgboost/pull/4808#issuecomment-530685400
- [ ]  remove duplicated colmn size check in train/eval datasets
- [x] cleanup duplicated rabit cmake build in xgboost pr https://github.com/dmlc/rabit/pull/106

**Comment by trivialfis** [comment]
Looks interesting. ;-)

**Comment by trams** [comment]
This looks interesting indeed. One question: "What is native distributed XGB training?" How can I use it? Is it the one which involves a python package + dask?

**Comment by chenqin** [comment]
> This looks interesting indeed. One question: "What is native distributed XGB training?" How can I use it? Is it the one which involves a python package + dask?

If you try xgboost with more than one machine. You are already using rabit, we added feature and track changes in progress to xgb layer

https://www.slideshare.net/ChenQin1/scaling-xgboost

**Comment by trams** [comment]
@chenqin, I understand that xgboost uses rabit as AllReduce implementation. I still don't really know what is a native distributed XGB training?
Does xgboost-spark run native distributed XGB training? If yes then why do we add "native" here? What other distributed XGB training do we have?

I am new to the project and I am still discovering different ways to use xgboost so this is an honest question.

**Comment by chenqin** [comment]
> @chenqin, I understand that xgboost uses rabit as AllReduce implementation. I still don't really know what is a native distributed XGB training?
> Does xgboost-spark run native distributed XGB training? If yes then why do we add "native" here? What other distributed XGB training do we have?
> 
> I am new to the project and I am still discovering different ways to use xgboost so this is an honest question.

In some use cases where user don't have complex feature generating needs, user can launch xgboost native worker (c++) without data processing 
framework. https://github.com/kubeflow/xgboost-operator

**Comment by chenqin** [comment]
from description in this thread, yes, dask-xgboost leverage rabit as well.
https://github.com/dmlc/xgboost/issues/2032

**Comment by hcho3** [comment]
@chenqin It's epic :)

**Comment by nateagr** [comment]
Hi there! Any update on this epic ? Thanks.

**Comment by chenqin** [comment]
> Hi there! Any update on this epic ? Thanks.

Yes, it's going (holiday session slow), still miss the final piece of patch XGBoost-spark after we can get current open pr landed.

**Comment by trivialfis** [comment]
I don't think this is possible in short term.  Let's stick with fail all strategy for now.  We @hcho3 are thinking about redesigning RABIT from scratch.
