### ISSUE TITLE
[CI] Potpourri of tasks for the CI server (xgboost-ci.net)

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#4916]
- [x] Install security updates to Jenkins and other software packages
- [x] For GPU test agents, use [G4 instance type](https://aws.amazon.com/ec2/instance-types/g4/) instead of current [P2 instance type](https://aws.amazon.com/ec2/instance-types/p2/). Compared to P2, G4 is more cost efficient and uses newer microarchitecture (Turing).
- [x] With the above, we can now add tests for cuDF. (#4792)
- [x] Upgrade Visual Studio 2017 to update 15.7, to get full support for C++11.
- [x] Store nightly build artifacts in a S3 bucket with organized names (#4813, #4752)
- [x] Fix SSL connection problem #4921

Feel free to make more suggestions.
@dmlc/xgboost-committer @trivialfis @rongou @sriramch

**Comment by hcho3** [comment]
As part of #4921, I upgraded GPU test agents to use G4 instance types. I only did it for the agents running Linux; I'll come back and update Windows agents later.
