### ISSUE TITLE
[Roadmap] DMatrix refactoring

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#5143]
This issue is a roadmap and checklist for ongoing work re-factoring DMatrix (see RFC #4354).

The first steps are to use a common interface to external data, unifying the way DMatrix objects are constructed and simplifying the process of adding new external data sources.

- [x] Create adapter interface to external data, implement constructors for SimpleDMatrix (#5044)
- [x] Extend data adapters to SparsePageDMatrix (#5092)
- [x] Extend data adapters to cudf data loading (#5108)
- [x] Add support for cupy (#5206)
- [x] Implement DMatrix slice via adapter (#5198)

After the above all DMatrix constructors will be happening via adapters, missing value handling and use of threads will be consistent.

Then I plan to start reducing the number of classes associated with DMatrix.
- [x] Remove SimpleCSRSource into SimpleDMatrix (#5315)
- [x] Remove SparsePageSource into SparsePageDMatrix

The final goal is to save memory by constructing histogram matrices for the `hist` and `gpu_hist` algorithms directly from external data using adapters. We will need some discussion on the interface e.g. if a user wants to build the histogram DMatrix directly, specify an enum to the constructor indicating  DMatrix type
- [x] Develop interface for instantiating histogram DMatrix directly
- [x] Build constructor for EllPack matrix directly using adapters

Lastly:
- [x] Enable weighted sketching for `DeviceQuantileDMatrix`.

**Comment by dattatreyam** [comment]
Hi, I am trying to generate a DaskDMatrix object from large dataframes and it is super slow. Is it expected to be slow ? If so, can you please help me understand why this is the case.

dtrain = DaskDMatrix(client, large_dask_dataframe_x, large_dask_dataframe_y) 

my large_dask_dataframe has few million examples ...

**Comment by trivialfis** [comment]
@dattatreyam Dask's computation is lazy, and `DaskDMatrix`'s constructor forces all lazy computation to materialize.  That means all your previous operations on dask's data structure like dataframe or array are carried out in the constructor of `DaskDMatrix`.

**Comment by JohnZed** [comment]
@RAMitchell - the steps look good to me, but I see you allude to implementing DMatrix slice functionality. Is this like selecting a subset of rows? Or columns? Sounds promising but I'd be curious to hear more what you have in mind for it.

**Comment by RAMitchell** [comment]
@JohnZed its functionality that already exists but needs to be ported to new code before all of the old code can be removed. It is a small job in this case.

**Comment by dattatreyam** [comment]
> @dattatreyam Dask's computation is lazy, and `DaskDMatrix`'s constructor forces all lazy computation to materialize. That means all your previous operations on dask's data structure like dataframe or array, including reading CSV file are carried out in the constructor of `DaskDMatrix`. See notes in: #5144

Thanks!

**Comment by sandys** [comment]
@JohnZed does it make sense for your issue filed on dask-ml to be incorporated here as well ? considering the new xgboost.dask interface.

https://github.com/dask/dask-ml/issues/605

**Comment by hcho3** [comment]
@trivialfis Can this issue now be closed, now that we have weighted quantile sketching on GPU?

**Comment by trivialfis** [comment]
@hcho3 Depends.  Do we wait for CPU impl?
