### ISSUE TITLE
[Roadmap] 1.0.2 patch release

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5342]
1.0.0 was a big release marking a milestone in the history of the XGBoost project. It is expected that some users will face issues as they upgrade from 0.90 to 1.0.0. After a week or so, I'd like to create a patch release that fixes a few urgent bugs.

Criteria for inclusion:
* The patch should fix an issue that was newly introduced in 1.0.0. Outstanding bugs that were present in 0.90 will not qualify.
* The patch should be small and do not present a high risk of breaking other functionalities. So a bug fix that requires a huge code change does not qualify.
* In general, the list here should be short, so no more than 5 patches.
* Two or three committers should agree to include it.

List of patches:
- [x] Fix a small typo in sklearn.py that broke multiple eval metrics (#5341)
- [x] Restore loading model from buffer. (#5360)
- [x] Use type name for data type check. (#5364)

@trivialfis @dmlc/xgboost-committer 

ps. Historically, we (maintainers) did not back port bug fixes to a previous release. We make exception here because 1.0.0 is a big jump from 0.90.

**Comment by trivialfis** [comment]
@hcho3 I think we are good to go now?

**Comment by hcho3** [comment]
Yes, I believe we can release a new patch release.

**Comment by hcho3** [comment]
1.0.2 is now available.
