### ISSUE TITLE
[Roadmap] 1.2.0 Roadmap

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5734]
@dmlc/xgboost-committer Please add your items here by editing this post. Let's ensure that

* Each item has to be associated with a ticket
* Major design/refactoring are associated with a RFC before committing the code
* Blocking issue must be marked as blocking
* Breaking change must be marked as breaking

For other contributors who have no permission to edit the post, please comment here about what you think should be in 1.2.0.

- [x] GPU port of Accelerated Failure Time objective for survival analysis (#5714)
- [x] Optimized JSON IO (#5772).
- [x] Callback function for device DMatrix (#5629).
- [x] Device DMatrix for dask interface (#5583, #5901).
- [x] Integrate dask interface with Python asyncio. (#5639, #5862)
- [x] Upgrade rabit. (#5680)

Blocking pull requests
- [x] https://github.com/dmlc/xgboost/pull/5934
- [x] https://github.com/dmlc/xgboost/pull/5929
- [x] #5171
- [x] https://github.com/dmlc/xgboost/pull/5853
- [x] #5940
- [x] #5862
- [x] https://github.com/dmlc/xgboost/pull/5954

Breaking change:
- [x] From now on R and Python custom evaluation metric will receive raw prediction. https://github.com/dmlc/xgboost/pull/5954

**Comment by thvasilo** [comment]
Regarding distributed learning, Databricks has this [big warning](https://docs.databricks.com/applications/machine-learning/third-party/index.html#xgboost-1) on their XGBoost docs: a cluster running Spark has to be re-started if an XGBoost job fails. 

This is bad user experience, as a shared cluster might be running a number of other things and it would have to be shut down when a job fails, killing everything else.

The related issue #4826 hasn't had an update in a long time, so not sure if that's still the case with 1.1.0.

**Comment by hcho3** [comment]
@ldesreumaux We would like to remove the experimental label after we make JSON serialization robust. #5772 adds a whole suite of tests to ensure that floating-point values are preserved by JSON serialization.

**Comment by trivialfis** [comment]
> I'll also bring up re-visiting the default parameters issue, #4986 and the linked issue there, 1.2.0 might be a good point to at least change the min_child_weight.

I think we will have to do it in next release.  Which is not a bad thing, I'm targeting cat data support so we might unify a lots of internal code and will be able to support a unified set of parameters.

**Comment by thvasilo** [comment]
Is categorical data support planned for 1.2.0 @trivialfis ?

**Comment by hcho3** [comment]
@dmlc/xgboost-committer It's been more than 2 months since we release 1.1.0, and we made 130 commits since then. Let's think about releasing 1.2.0 soon. Consider which pull requests are blocking.

**Comment by CodingCat** [comment]
I think https://github.com/dmlc/xgboost/pull/5929 is definitely something BLOCKING 

https://github.com/dmlc/xgboost/pull/5171 is something good to have as the first version supporting Spark 3.0 with a GPU capability

**Comment by trivialfis** [comment]
- [ ] New callback functions (#5612)
- [ ] Expose rabit context for dask interface. (#5765, #5408)

Removed from the roadmap.

**Comment by hcho3** [comment]
Added blocking PRs

**Comment by wbo4958** [comment]
I can add gpu_hist unit test today, @CodingCat @hcho3

**Comment by hcho3** [comment]
@wbo4958 I marked gpu_hist as "blocking". We'll make sure it's included in 1.2.0.

**Comment by hcho3** [comment]
@thvasilo Categorical data support won't be included in 1.2.0. cc @trivialfis

**Comment by trivialfis** [comment]
@hcho3 Can branch out?

**Comment by hcho3** [comment]
Sure, let me do that this Friday.

**Comment by hcho3** [comment]
Now that all blocking PRs have been merged, let me prepare a new release branch.

**Comment by hcho3** [comment]
1.2.0 is now released.
