### ISSUE TITLE
[Roadmap] 1.1.1 Patch Release

### ISSUE THREAD

**Issue by hcho3** [dmlc/xgboost#5735]
We are looking to release a patch release 1.1.1, primarily to benefit from CPU performance improvement in the PyPI wheels (#5720). I'd like to know if there are other patches that should go into 1.1.1.

@dmlc/xgboost-committer 

List of patches:
- [x] CPU performance improvement in the PyPI wheels (#5720)
- [x] Fix loading old model. (#5724)
- [x] Install pkg-config file (#5744)

**Comment by kongzii** [comment]
I am not sure that this counts as a patch, but if so, it would be awesome to have it in the release: https://github.com/dmlc/xgboost/pull/5744

**Comment by hcho3** [comment]
@kongzii The patch release will be released as compiled binaries. Wouldn't someone who want to use pkgconfig be compiling XGBoost from the source?

**Comment by kongzii** [comment]
@hcho3 I thought that if it would be in the patch release, then doing `brew install xgboost` would add pkg-config along with it, or do I need to do another update for it to work like that?
And there are also branches for releases, so `git checkout release_1.1.1` would have pkg-config in it.

**Comment by hcho3** [comment]
@kongzii Ah I forgot about Homebrew. Yes, indeed, Homebrew will run `make install` and install the pkg-config. We'll add it to the release.

**Comment by kongzii** [comment]
Thank you  👍

**Comment by SmirnovEgorRu** [comment]
@hcho3, I suppose we can close the first task, performance of this was checked by @ShvetsKS 
* [X] CPU performance improvement in the PyPI wheels (#5720)

**Comment by hcho3** [comment]
1.1.1 is now available from PyPI. To install, run `python -m pip install xgboost==1.1.1`.
