### ISSUE TITLE
[Roadmap] 1.3.0 Roadmap

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6031]
@dmlc/xgboost-committer Please add your items here by editing this post. Let's ensure that

* Each item has to be associated with a ticket
* Major design/refactoring are associated with a RFC before committing the code
* Blocking issue must be marked as blocking
* Breaking change must be marked as breaking

For other contributors who have no permission to edit the post, please comment here about what you think should be in 1.3.0.

- [x] Merge rabit into XGBoost (#5995, #6023)
- [x] GPU Shap value compuation. (#6038, #6064,  #6163)
- [x] Let Spark package fail gracefully (#4826, #6019)
- [x] Support for more different meta on dask. (#6130, #6132)
- [x] Support MAPE. (#6119)
- [x] GPU predict leaf function (#5847, #6187)
- [x] New callback functions (#5612, #6199)
- [x] Early stopping on dask. (#6199)
- [x] Initial support for categorical data. (#5949, #6137, #6140, #6164, #6165, #6166, #6179, #6194, #6219)
- [x] Feature weights for column sampling (exact, hist, gpu_hist) (#5962)
- [x] Slicing model. (#5531, #4052, #6302)
- [x] Default to JSON for memory snapshot. (#6027)
- [x] Support dask on reverse proxy environment. (#5765, #5408, #6142, #6343)
- [x] Support using system installation of `libxgboost.so` when distributing Python package. (#6362)

**Comment by trivialfis** [comment]
Moving:

- [ ] Support dask on reverse proxy environment. (#5765, #5408, #6142)

off the list.  Getting it work on GKE is a bit tricky.  Related:
- dask kubernetes: https://kubernetes.dask.org/en/latest/
- kubernetes
- GKE
- RABIT internal

**Comment by trivialfis** [comment]
The item is moved back in now that I can run tests myself.

**Comment by trivialfis** [comment]
RC1 is targeted at Nov 20.
