### ISSUE TITLE
[Roadmap] 1.3.2 Patch release

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6571]
We are looking to release a patch release 1.3.2.

This issue will remain open until January 11, 2021.

@dmlc/xgboost-committer 

Pull requests:

- [x] https://github.com/dmlc/xgboost/pull/6555 Fix compatibility with newer scikit-learn.
- [x] https://github.com/dmlc/xgboost/pull/6569 Fix wrong `best_ntree_limit` in multi-class.
- [x] https://github.com/dmlc/xgboost/issues/6542#issuecomment-755044276 https://github.com/dmlc/xgboost/pull/6578 #6606 Ensure that Rabit can be compiled on Solaris
- [x] #6579 Fix `best_ntree_limit` for linear and dart.
- [x] https://github.com/dmlc/xgboost/pull/6592 Remove duplicated DMatrix.
- [x] https://github.com/dmlc/xgboost/pull/6594 Fix evals_result in ranker.

**Comment by trivialfis** [comment]
@hcho3 All merged now.

**Comment by hcho3** [comment]
@trivialfis Great! Why don't you give a shot at making the patch release? Use #6543 as a template.

**Comment by trivialfis** [comment]
Thanks for the suggestion, let me do that tomorrow.

**Comment by trivialfis** [comment]
@hcho3 @hetong007  I created a release page.  Next would be submitting packages to pip and cran.

**Comment by hetong007** [comment]
@trivialfis I uploaded this branch onto R-hub, and it still reports error: https://builder.r-hub.io/status/xgboost_1.3.2.1.tar.gz-f47cc590f1434dddb4c4b89cd02703dc

This error is from R-hub with platform `Oracle Solaris 10, x86, 32 bit, R-release, Oracle Developer Studio 12.6`. This matches the compiler of CRAN Solaris: https://cran.r-project.org/web/checks/check_flavors.html#r-patched-solaris-x86

**Comment by trivialfis** [comment]
Em .. failing to install

**Comment by hcho3** [comment]
![image](https://user-images.githubusercontent.com/2532981/104610241-bdf46580-5638-11eb-9d12-ffe3e95ccc7d.png) The link shows success?

**Comment by trivialfis** [comment]
Looked a little bit closer:

```
4118#> * checking for sufficient/correct file permissions ... OK

4119#> * checking whether package ‘xgboost’ can be installed ... ERROR

4120#> Installation failed.

4121#> See ‘/export/home/XnXaLcc/xgboost.Rcheck/00install.out’ for details.
```

**Comment by trivialfis** [comment]
I don't know if there's a way to retrieve that log.

**Comment by hetong007** [comment]
@trivialfis Seems this is the log: https://artifacts.r-hub.io/xgboost_1.3.2.1.tar.gz-e506d18ec1084d778d4e8299a3d57e91/xgboost.Rcheck/

**Comment by trivialfis** [comment]
Got it passed: https://builder.r-hub.io/status/xgboost_1.3.2.1.tar.gz-72aa615847ba65333ecfea61c676b7b4  Will open a PR.

**Comment by trivialfis** [comment]
https://github.com/dmlc/xgboost/pull/6606

**Comment by hetong007** [comment]
I patched this PR and submitted it to R-hub again, but got an error in installation: https://artifacts.r-hub.io/xgboost_1.3.2.1.tar.gz-5c8a82e1e66188afea79817c398575fd/xgboost.Rcheck/00install.out

**Comment by trivialfis** [comment]
`std::ctype<char>::id` ?  @hetong007 what's your configuration of testing?

**Comment by hetong007** [comment]
My configuration on r-hub is: 

- Visit https://builder.r-hub.io/advanced
- Select `Oracle Solaris 10, x86, 32 bit, R-release, Oracle Developer Studio 12.6` for the platform -- This is the CRAN Soalris config.
- Upload the package, configure the email address
- Start the check and wait.

I can submit again to see if this is a false alarm, will update this thread if ends up with a different result.

**Comment by trivialfis** [comment]
I hope that we don't have to bisect it on R Hub ....

**Comment by trivialfis** [comment]
I tried the old 1.2 release, which is also failing.

**Comment by hetong007** [comment]
Seems the current CRAN error is not the same as what we have on r-hub: https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/xgboost-00install.html

**Comment by trivialfis** [comment]
@hetong007 That was fixed in https://github.com/dmlc/xgboost/pull/6578

**Comment by trivialfis** [comment]
At latest 1.3 branch, all compiler related workarounds/fixes are applied.  But the linker issue you found https://github.com/dmlc/xgboost/issues/6571#issuecomment-760575026 is still there, and I'm not sure how to remove it.  The `std::ctype<char>::id` seems to be used in std stream, but I'm not sure which part of xgboost is triggering that error.

**Comment by trivialfis** [comment]
@hetong007 Can we just submit the package?

**Comment by hetong007** [comment]
Well if a fix is not easily accessible, I can try to submit. That's at least an action trying to patch.

**Comment by trivialfis** [comment]
@hetong007 Thanks!   Please keep me on the loop if there's any insight on the linker error.  I wonder if it's reproducible on CRAN.  Since of the 2 Solaris configurations on R Hub, the one that without oracle developer studio is passing.

**Comment by trivialfis** [comment]
@hcho3 All wheels are uploaded to pypi.  Many thanks for the help!
