### ISSUE TITLE
[Roadmap] 1.5.0 Roadmap

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6846]
@dmlc/xgboost-committer Please add your items here by editing this post. Let's ensure that

* Each item has to be associated with a ticket
* Major design/refactoring are associated with a RFC before committing the code
* Blocking issue must be marked as blocking
* Breaking change must be marked as breaking

For other contributors who have no permission to edit the post, please comment here about what you think should be in 1.5.0.

- [ ] Improve ranking implementation. (#6450)
- [ ] Further development on categorical data support. (#6503)
- [ ] Staged predict (#5006)
- [ ] Add score tree interval to early stopping. (#5238, #5090)

**Comment by stevendavis** [comment]
+1 for Revising ranking objectives. #6450

**Comment by Shadyelgewily** [comment]
+1 for ([XGBoost4J-Spark] Early stopping and best iteration)  [#6893](https://github.com/dmlc/xgboost/issues/6893)

**Comment by trivialfis** [comment]
- [ ] Add score tree interval to early stopping. (#5238, #5090)
- [ ] Improve ranking implementation. (#6450)

Moving the 2 items to the next release.  I will start planning the release before the end of next week.
