### ISSUE TITLE
[Roadmap] 1.4.1 Patch release

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6867]
This will be a bug fix release after 1.4.  Please comment if you think there are commits that should be backported.
@dmlc/xgboost-committer

PRs to be backported:

- [x] https://github.com/dmlc/xgboost/pull/6866

TODOs:
- [x] Bump version. (https://github.com/dmlc/xgboost/pull/6874) .
- [x] github release.
- [x] Source tar ball.
- [x] pip release.
- [x] CRAN release. https://github.com/dmlc/xgboost/issues/6793
- [x] maven release. https://github.com/dmlc/xgboost/issues/6793
- [x] NEWS.md (#6876)

**Comment by hcho3** [comment]
I've just released 1.4.1 to Maven Central. The artifacts will become available momentarily.

**Comment by hcho3** [comment]
XGBoost4J 1.4.1 is now on Maven Central: https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.12/1.4.1/.
