### ISSUE TITLE
[Roadmap] 1.4.2 Patch release

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6920]
This will be a bug fix release after 1.4.1. Please comment if you think there are commits that should be backported.
@dmlc/xgboost-committer

The release is planned to be Python only with following patches:

- [x] CI fixes (https://github.com/dmlc/xgboost/pull/6933).
- [x] https://github.com/dmlc/xgboost/pull/6889
- [x] Fix for updated cupy with `lazy_isinstance`. (https://github.com/dmlc/xgboost/pull/6933)
- [x] https://github.com/dmlc/xgboost/pull/6927
- [x] https://github.com/dmlc/xgboost/pull/6947
