### ISSUE TITLE
1.5.0 Release Candidate

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#7260]
Roadmap https://github.com/dmlc/xgboost/issues/6846 . Draft of release note: https://github.com/dmlc/xgboost/pull/7271 .

We are about to release version 1.5.0 of XGBoost. In the next two weeks, we invite everyone to try out the release candidate (RC).

Feedback period: until the end of *October 13, 2021*. No new feature will be added to the release; only critical bug fixes will be added.

@dmlc/xgboost-committer

### Available packages:

- **Python packages**:

``` bash
pip install xgboost==1.5.0rc1
```

- **R packages**:
Linux x86_64: https://github.com/dmlc/xgboost/releases/download/v1.5.0rc1/xgboost_r_gpu_linux.tar.gz
Windows x86_64: https://github.com/dmlc/xgboost/releases/download/v1.5.0rc1/xgboost_r_gpu_win64.tar.gz

``` bash
R CMD INSTALL ./xgboost_r_gpu_linux.tar.gz
```

- **JVM packages**

<details><summary>Show instructions (Maven/SBT)</summary>
<p>

Maven
```xml
<dependencies>
  ...
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j_2.12</artifactId>
      <version>1.5.0-RC1</version>
  </dependency>
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-spark_2.12</artifactId>
      <version>1.5.0-RC1</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>XGBoost4J Release Repo</id>
    <name>XGBoost4J Release Repo</name>
    <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/</url>
  </repository>
</repositories>
```

SBT
```scala
libraryDependencies ++= Seq(
  "ml.dmlc" %% "xgboost4j" % "1.5.0-RC1",
  "ml.dmlc" %% "xgboost4j-spark" % "1.5.0-RC1"
)
resolvers += ("XGBoost4J Release Repo"
              at "https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/")
```
</p>
</details>

Starting from 1.2.0, XGBoost4J-Spark supports training with NVIDIA GPUs. To enable this capability, download artifacts suffixed with `-gpu`, as follows:

<details><summary>Show instructions (Maven/SBT)</summary>
<p>

Maven
```xml
<dependencies>
  ...
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-gpu_2.12</artifactId>
      <version>1.5.0-RC1</version>
  </dependency>
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-spark-gpu_2.12</artifactId>
      <version>1.5.0-RC1</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>XGBoost4J Release Repo</id>
    <name>XGBoost4J Release Repo</name>
    <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/</url>
  </repository>
</repositories>
```

SBT
```scala
libraryDependencies ++= Seq(
  "ml.dmlc" %% "xgboost4j-gpu" % "1.5.0-RC1",
  "ml.dmlc" %% "xgboost4j-spark-gpu" % "1.5.0-RC1"
)
resolvers += ("XGBoost4J Release Repo"
              at "https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/")
```
</p>
</details>

### TO-DOs

- [x] Release pip rc package.
- [x] Test on R-hub.
- [x] Release R rc package.
- [x] Release jvm rc packages.

### PRs to be backported
- [x] Fix gamma negative log likelihood (https://github.com/dmlc/xgboost/pull/7275)
- [x] Fix `verbose_eval` in Python `cv` function. (https://github.com/dmlc/xgboost/pull/7291)
- [x] Fix weighted samples in multi-class AUC (https://github.com/dmlc/xgboost/pull/7300)
- [x] Fix prediction with categorical dataframe using sklearn interface. (https://github.com/dmlc/xgboost/pull/7306)

**Comment by trivialfis** [comment]
This time R-hub has Apple M1 instances.  Let's wait for the test result. ;-)

**Comment by trivialfis** [comment]
* TODO R-Hub
  - [X] Apple Silicon (M1), macOS 11.6 Big Sur, R-release
    https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-bc54ff86ce58fe30b3a2562c4695372f
  - [X] Oracle Solaris 10, x86, 32 bit, R-release
    https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-eeb1a18511be2a4808f1fbacabae3924
  - [ ] Oracle Solaris 10, x86, 32 bit, R release, Oracle Developer Studio 12.6
    https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-3bfc8dc9cfc29ab47f94d96494acae03
    ERROR
```
config.status: creating src/Makevars
 ** libs
Makevars:17: -DXGBOOST_STRICT_R_MODE=1
Makevars:17: -DDMLC_LOG_BEFORE_THROW=0
Makevars:17: -DDMLC_ENABLE_STD_THREAD=1
Makevars:17: -DDMLC_DISABLE_STDIN=1
Makevars:17: -DDMLC_LOG_CUSTOMIZE=1
Makevars:17: -DXGBOOST_CUSTOMIZE_LOGGER=1
Makevars:17: -DRABIT_CUSTOMIZE_MSG_
/opt/developerstudio12.6/bin/CC -std=c++14 -I"/opt/R/R-4.1.1/lib/R/include" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=1 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_  -I/opt/csw/include  -DDMLC_CMAKE_LITTLE_ENDIAN=1 -pthread  -KPIC  -O -xlibmil -xtarget=native -xcache=generic -nofstore  -c xgboost_R.cc -o xgboost_R.o
CC: Warning: Option -pthread passed to ld, if ld is invoked, ignored otherwise

"xgboost_R.cc", assertion failed in function pr_post_process_node() @ preopt.c:3862
assert(nd_eq_(scope_first_stmt_(node), first_s))

CC: ube failed for xgboost_R.cc
gmake: *** [/opt/R/R-4.1.1/lib/R/etc/Makeconf:175: xgboost_R.o] Error 2
ERROR: compilation failed for package â€˜xgboostâ€™
 * removing â€˜/export/home/Xdub2Tz/R/xgboostâ€™
 * restoring previous â€˜/export/home/Xdub2Tz/R/xgboostâ€™
```
  - [X] Windows Server 2008 R2 SP1, R-release, 32/64 bit
    https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-dfce4f6c30ab1ea37453ade2d2f6ab39
  - [X] Ubuntu Linux 20.04.1 LTS, R-release, GCC
    https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-d8c8de0e432866a8893219de27189b58
  - [ ] CentOS 8, stock R from EPEL
    https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-a2834eeda7615d3bc96697b0c48f2392
    xgboost 1.5.0.1: PREPERROR
    Second run:
    https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-d66aa2b88da2a1ef57a0bd162afa617f
```
14715docker rm xgboost_1.5.0.1.tar.gz-d66aa2b88da2a1ef57a0bd162afa617f-1

14716#> Error: No such container: xgboost_1.5.0.1.tar.gz-d66aa2b88da2a1ef57a0bd162afa617f-1

14717true

14718docker rm xgboost_1.5.0.1.tar.gz-d66aa2b88da2a1ef57a0bd162afa617f-2
```

**Comment by trivialfis** [comment]
Hi all, the RC packages are released to public repositories now.  Please help test the new release and provide feedbacks.  Enjoy!

**Comment by trivialfis** [comment]
Hi @hetong007 @hcho3 I have made the 1.5 stable release and uploaded all Python packages to pypi.  Could you please help upload the R package and JVM packages?

**Comment by hcho3** [comment]
@trivialfis I've uploaded the JVM package to Maven Central.

**Comment by hetong007** [comment]
I'm quite occupied these two days but I'll start submitting the R package later this week. Hope it'll go into cran smoothly.

**Comment by trivialfis** [comment]
I will ask on the devel list.

**Comment by trivialfis** [comment]
Hmm, R-hub also has this include path:

```
"C:/rtools40/mingw32/bin/"g++ -std=gnu++14 -I"C:/PROGRA~1/R/R-4.1.1/include" -DNDEBUG -I./include -I./dmlc-core/include -I./rabit/include -I. -DXGBOOST_STRICT_R_MODE=1 -DDMLC_LOG_BEFORE_THROW=0 -DDMLC_ENABLE_STD_THREAD=0 -DDMLC_DISABLE_STDIN=1 -DDMLC_LOG_CUSTOMIZE=1 -DXGBOOST_CUSTOMIZE_LOGGER=1 -DRABIT_CUSTOMIZE_MSG_ -DDMLC_CXX11_THREAD_LOCAL=0 -I"c:/R/local330/include" -fopenmp -DDMLC_CMAKE_LITTLE_ENDIAN=1 -pthread -O2 -Wall -mfpmath=sse -msse2 -mstackrealign -c xgboost_R.cc -o xgboost_R.o
```

**Comment by trivialfis** [comment]
I have passed the test by reverting the `nthread` commit. https://win-builder.r-project.org/FGUxY7NN55DR

**Comment by trivialfis** [comment]
Reproduced the error locally.

**Comment by hetong007** [comment]
Thanks, that's fantastic! Would you mind to leave a pointer to the exact commit?

There seems to be two ways to handle this:

- Revert the commit in the CRAN submission. What would be the potential risk for CRAN users?
- Bypass the relevant test. Is it easy to do so?

**Comment by trivialfis** [comment]
@hetong007 I opened a PR for the fix: https://github.com/dmlc/xgboost/pull/7390 .

**Comment by trivialfis** [comment]
@hetong007 Hi, I ran some tests on 1.5 branch a3d195e73e521c1d7fb9e0557f440cb46517b5da .

Oracle Solaris 10, x86, 32 bit, R-release
https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-b12024d745fb520bb620a93ec8d0cd23

Windows Server 2008 R2 SP1, R-release, 32/64 bit
https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-5d5a4fccd237b333ae66e75769402098

Apple Silicon (M1), macOS 11.6 Big Sur, R-release
https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-a02348f284ffc3f333c0154c5a002f4d

win builder
https://win-builder.r-project.org/2N8h4HeU2gr1

**Comment by hetong007** [comment]
Thanks a lot! I've submitted the latest release branch to CRAN. It passes the auto-check, however seems to break some dependencies. I'll need to look into these packages, and probably communicate with the maintainers before we can have it in CRAN.

Details are below:

```
Dear maintainer,

package xgboost_1.5.0.1.tar.gz has been auto-processed. The auto-check found problems when checking the first order strong reverse dependencies.
Please reply-all and explain: Is this expected or do you need to fix anything in your package? If expected, have all maintainers of affected packages been informed well in advance? Are there false positives in our results?

*** Changes to worse in reverse dependencies ***
Debian: <https://win-builder.r-project.org/incoming_pretest/xgboost_1.5.0.1_20211104_073948/reverseDependencies/summary.txt>

Log dir: <https://win-builder.r-project.org/incoming_pretest/xgboost_1.5.0.1_20211104_073948/>
The files will be removed after roughly 7 days.

Pretests:
Windows: <https://win-builder.r-project.org/incoming_pretest/xgboost_1.5.0.1_20211104_073948/Windows/00check.log>
Debian: <https://win-builder.r-project.org/incoming_pretest/xgboost_1.5.0.1_20211104_073948/Debian/00check.log>

Last published version on CRAN:

CRAN Web: <https://cran.r-project.org/package=xgboost>

Best regards,
CRAN teams' auto-check service
Package check result: OK

Changes to worse in reverse depends:

Package: EIX
Check: re-building of vignette outputs
New result: WARNING
  Error(s) in re-building vignettes:
    ...
  --- re-building ‘EIX.Rmd’ using rmarkdown
     [[ suppressing 19 column names 'satisfaction_level', 'last_evaluation', 'number_project' ... ]]
  Warning: ggrepel: 2 unlabeled data points (too many overlaps). Consider increasing max.overlaps
  Quitting from lines 157-165 (EIX.Rmd)
  Error: processing vignette ‘EIX.Rmd’ failed with diagnostics:
  non-numeric matrix extent
  --- failed re-building ‘EIX.Rmd’

  --- re-building ‘titanic_data.Rmd’ using rmarkdown
  Warning: ggrepel: 4 unlabeled data points (too many overlaps). Consider increasing max.overlaps
  Quitting from lines 81-86 (titanic_data.Rmd)
  Error: processing vignette ‘titanic_data.Rmd’ failed with diagnostics:
  non-numeric matrix extent
  --- failed re-building ‘titanic_data.Rmd’

  SUMMARY: processing the following files failed:
    ‘EIX.Rmd’ ‘titanic_data.Rmd’

  Error: Vignette re-building failed.
  Execution halted

Package: radiant.model
Check: tests
New result: ERROR
    Running ‘testthat.R’ [4s/4s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > ## use shift-cmd-t to run all tests
    > library(testthat)
    > test_check("radiant.model")
    Loading required package: radiant.model
    Loading required package: radiant.data
    Loading required package: magrittr

    Attaching package: 'magrittr'

    The following objects are masked from 'package:testthat':

        equals, is_less_than, not

    Loading required package: ggplot2
    Loading required package: lubridate

    Attaching package: 'lubridate'

    The following objects are masked from 'package:base':

        date, intersect, setdiff, union

    Loading required package: tidyr

    Attaching package: 'tidyr'

    The following object is masked from 'package:magrittr':

        extract

    The following object is masked from 'package:testthat':

        matches

    Loading required package: dplyr

    Attaching package: 'dplyr'

    The following object is masked from 'package:testthat':

        matches

    The following objects are masked from 'package:stats':

        filter, lag

    The following objects are masked from 'package:base':

        intersect, setdiff, setequal, union


    Attaching package: 'radiant.data'

    The following objects are masked from 'package:lubridate':

        month, wday

    The following object is masked from 'package:ggplot2':

        diamonds

    The following object is masked from 'package:magrittr':

        set_attr

    The following object is masked from 'package:testthat':

        describe

    The following object is masked from 'package:base':

        date

    SI1     9 114304.420 104924.680 123684.159  9379.739
    sex|male    0.080 -92.0%      -2.522     0.163 -15.447  < .001 ***
    2nd female      0.779 0.712 0.833
    1st female      0.896 0.856 0.926
    1st female 29.000      0.919 0.880 0.945
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Failure (test_stats.R:160:3): Gradient Boosting - NoLD test ─────────────────
    `res1` not equal to `res2`.
    3/3 mismatches (average diff: 0.062)
    [1] 0.847 - 0.758 ==  0.089
    [2] 0.117 - 0.210 == -0.093
    [3] 0.036 - 0.032 ==  0.004

    [ FAIL 1 | WARN 0 | SKIP 0 | PASS 25 ]
    Error: Test failures
    Execution halted
```

**Comment by trivialfis** [comment]
It shouldn't have breaking change (but has new deprecation)   I will look into it.

**Comment by hetong007** [comment]
From the above log, the error from `EIX` doesn't seem directly relevant, while the error from `radiant.model` seems to be relevant, as our new version might train the model differently and lead to different prediction values.

**Comment by trivialfis** [comment]
Building that package now.  Might take some time to debug, I'm working on other things at the moment.  Will keep you posted.

**Comment by trivialfis** [comment]
663136aa08c00598d8b49adf5901e4cb2ce187da is the commit to blame.

**Comment by trivialfis** [comment]
Okay, I get the issue now.  I re-implemented the global feature importance in C++ to eliminate the text parsing.  But there's a subtle difference between the original Python and R implmentation.  For Python there were "total_gain" and "gain", the latter is just the former divided by split count (or "frequence" in R).  But for R this should not occur.

**Comment by trivialfis** [comment]
Opened a PR for the fix https://github.com/dmlc/xgboost/pull/7394 .  Sorry about the inconvenience and thanks for all the help!

**Comment by trivialfis** [comment]
Ran tests on R-hub and win-builder

# Passing:
* DONE macOS 10.13.6 High Sierra, R-release, CRAN's setup
  CLOSED: [2021-11-06 Sat 00:25]
https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-d08bc035dd41b34b66d1b17d125c9b42

* DONE Oracle Solaris 10, x86, 32 bit, R-release
  CLOSED: [2021-11-06 Sat 01:01]
https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-c860596701458ffb6ae601e3355ea344

* DONE Win-builder
  CLOSED: [2021-11-06 Sat 00:18]
https://win-builder.r-project.org/4G865eF9BYWv/

* DONE EIX
  CLOSED: [2021-11-06 Sat 00:25]

* DONE radiant.model
  CLOSED: [2021-11-06 Sat 00:25]

# Still running
* Debian Linux, R-release, GCC
https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-83dd71cbb5c091af5f3d374f7a4d5132

* CentOS 8, stock R from EPEL
https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-dff2ce990e710158c986a834af85c708

# Failing:
* Windows Server 2008 R2 SP1, R-release, 32/64 bit
  Failed
https://builder.r-hub.io/status/xgboost_1.5.0.1.tar.gz-7611c479e76f26550e3d61dc98388a5e


The windows instance on R-hub failed during "download and unpack files", which doesn't seem to be related to XGBoost:


```
 106#> windows_tracing_logfile C:\BVTBin\Tests\installpackage\csilogfile.log
 107#> setting _R_CHECK_FORCE_SUGGESTS_ to false
 108#> setting R_COMPILE_AND_INSTALL_PACKAGES to never
 109#> setting _R_CHECK_THINGS_IN_CHECK_DIR_ to false
 110#> setting R_REMOTES_STANDALONE to true
 111#> setting R_REMOTES_NO_ERRORS_FROM_WARNINGS to true
 112#> Exception calling "Start" with "0" argument(s): "The system cannot find the
 113#> file specified"
 114#> At C:\Users\USERdQIgyZGwrB\slave.ps1:124 char:5
 115#> + [void]$Process.Start()
 116#> + ~~~~~~~~~~~~~~~~~~~~~~
 117#> + CategoryInfo : NotSpecified: (:) [], MethodInvocationException
 118#> + FullyQualifiedErrorId : Win32Exception
 119#>
 120#> Exception calling "BeginOutputReadLine" with "0" argument(s): "StandardOut has
 121#> not been redirected or the process hasn't started yet."
 122#> At C:\Users\USERdQIgyZGwrB\slave.ps1:127 char:5
 123#> + $Process.BeginOutputReadLine()
 124#> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 125#> + CategoryInfo : NotSpecified: (:) [], MethodInvocationException
 126#> + FullyQualifiedErrorId : InvalidOperationException
 127#>
 128#> Exception calling "BeginErrorReadLine" with "0" argument(s): "StandardError
 129#> has not been redirected."
 130#> At C:\Users\USERdQIgyZGwrB\slave.ps1:128 char:5
 131#> + $Process.BeginErrorReadLine()
 132#> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 133#> + CategoryInfo : NotSpecified: (:) [], MethodInvocationException
 134#> + FullyQualifiedErrorId : InvalidOperationException
 135#>
 136#> Build timed out (after 30 minutes). Marking the build as failed.
 137#> Build was aborted
 138#> Pinging https://builder.r-hub.io/build/FAILURE/xgboost_1.5.0.1.tar.gz-7611c479e76f26550e3d61dc98388a5e
```

**Comment by trivialfis** [comment]
2 failures caused by timeout.  The tests have passed, but timeout at building doc.

This on centos is concerning:
```
14037#> * checking compiled code ... WARNING

14038#> File ‘xgboost/libs/xgboost.so’:

14039#> Found ‘abort’, possibly from ‘abort’ (C)

14040#> Objects: ‘./xgboost_R.o’, ‘./amalgamation/xgboost-all0.o’,

14041#> ‘./amalgamation/dmlc-minimum0.o’, ‘./rabit/src/allreduce_base.o’

14042#> Found ‘printf’, possibly from ‘printf’ (C)

14043#> Objects: ‘./xgboost_R.o’, ‘./amalgamation/xgboost-all0.o’,

14044#> ‘./amalgamation/dmlc-minimum0.o’, ‘./rabit/src/allreduce_base.o’

14045#> Compiled code should not call entry points which might terminate R nor
```

**Comment by trivialfis** [comment]
Doesn't make sense locally, I checked the binary, there's only `__snprintf_chk`.  I couldn't download the artifacts from R-hub due to not found error.

**Comment by hetong007** [comment]
@trivialfis Thanks a ton for digging into this! It has successfully passed the reverse dependency test, and on its way to CRAN. Let's hope it'll pass the real tests across all platforms :)

**Comment by trivialfis** [comment]
@hetong007 Do you have the bandwidth to review R PRs?  My experience with R is very limited and would be great to have an expert at supervising. ;-)

**Comment by hetong007** [comment]
No problem. I can still handle the R part, but not familiar with things that touch low-level source now.

**Comment by trivialfis** [comment]
Excellent!

**Comment by hetong007** [comment]
There might be some warnings we need to fix:

> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_xgboost.html>.
> 
> Please correct before 2021-11-22 to safely retain your package on CRAN.

**Comment by trivialfis** [comment]
Opened a PR: https://github.com/dmlc/xgboost/pull/7404  I did not reproduce the warning using the development version of clang though.

**Comment by trivialfis** [comment]
Running tests on R-hub and win-builder.  I will update this comment accordingly:

* macOS 10.13.6 High Sierra, R-release, CRAN's setup
https://builder.r-hub.io/status/xgboost_1.5.0.2.tar.gz-e9c7c56cffc1d61f47ea467845f81f7f

* Windows Server 2008 R2 SP1, R-release, 32/64 bit
https://builder.r-hub.io/status/xgboost_1.5.0.2.tar.gz-96afb982c2464daa5431b73fb27d9d61

* Oracle Solaris 10, x86, 32 bit, R-release
https://builder.r-hub.io/status/xgboost_1.5.0.2.tar.gz-a5b8f989c199a8d9a474cfde835df374

* Debian Linux, R-release, GCC
https://builder.r-hub.io/status/xgboost_1.5.0.2.tar.gz-9bbf8e8c8353e4e2b186e2a6035fff02

**Comment by trivialfis** [comment]
@hetong007 Should I bump the version to 1.5.0.2 or 1.5.1?  We are preparing the 1.5.1 for Python and JVM and it would be great to have some consistency.  But I'm not entirely sure about the CRAN policy.  Right now, the other 2 packages use `<major, minor, patch>` release naming format.

**Comment by hetong007** [comment]
Do we plan 1.5.1 to include ONLY the incremental fixes for CRAN submission? 

If so, we can bump to 1.5.1, otherwise I think it is better to use 1.5.0.2.

**Comment by trivialfis** [comment]
Got it, I will keep it as 1.5.0.2.  Opened a PR for incrementing the version number: https://github.com/dmlc/xgboost/pull/7452 .

**Comment by trivialfis** [comment]
All tests have passed.

**Comment by trivialfis** [comment]
Closing as all 1.5.0 packages are submitted.  Thank you all!
