### ISSUE TITLE
[Brick] XGBoost Brick Major Refactor

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#736]
I just merged https://github.com/dmlc/xgboost/pull/735 (see the PR for change logs) into the [brick branch](https://github.com/dmlc/xgboost/tree/brick)
This is a major refactor of xgboost core library, the library itself won't be faster, but cleaner and will be *easier to extend* in some sense.

This is the second major refactor of xgboost. The first one, named unity, aims at modularize xgboost, so we have the features such as distributed version, external memory version and different algorithms in one unified project. 

xgboost has doing great since the unity version has release. It is fast, works for many languages, and scales to billions of examples. However, up till now, the project still stands in a way as a blackbox of wrapper libraries, but only aimed to be used as a whole piece.  
-  It is hard to extend the core library,  for example to add support for new data format (e.g. directly pull data from SQL server). 
- It is also less obvious on how to use the library as parts, e.g. only use the tree builder or add user defined tree builders without touching the original projects.

These factors motivate this major refactor, aiming to make xgboost the fast, extensible as ```bricks```. So the user and developer can take the bricks in xgboost library, and plug them into their own system, or create extensions to plug things back. The library for language bindings are no longer called ```libxgboostwrapper```, but simply becomes ```libxgboost```.

- All the modules now switches to a registry pattern. The data parser, metric, objective function, tree builders are all backward registered to the registry in startup.
   - This means user only need to compile their code, for example in [xgboost/plugin](https://github.com/dmlc/xgboost/tree/brick/plugin) folder and directly register their extensions to xgboost *without need to touch the main library code*
- The user facing (library)interface are moved to [include](https://github.com/dmlc/xgboost/tree/brick/include/xgboost), with clear documentation on all functions and - Everything is now c++11. This means shorter and cleaner code, same random number(```std::mt19937```).
- The model should be backward compatible on 64bit, and 64/32 bit should be able to load the same model file, to help porting the models to different platforms(e.g. mobiles)

The goal is to make xgboost a library that can easily configured to take any data, runs on any platform and being easily integrated into major production system. This is an ambitious goal and maybe we are not there yet, but hopefully this is a good step.

Working Items
-------------------
- [x] Reconfigure the travis script to make sure we run on travis
- [x] Windows project is outdated, I am thinking of switching to CMake for windows, need a volunteer on this
   - Temporary switch to mingw solution, will need volunteer to add cmake later
- [x] Create a release tag for current master, we can discuss the version number, either 0.5 or 0.45 is fine.
- [x] Move distributed xgboost instruction to doc folder.

R Library
------------
Should be able to install via ```R CMD INSTALL```, install github may not work due to submodule, need to update instructions.
- [ ] Setup drat release workflow, in https://github.com/dmlc/drat
- [x] Decide if we want to reuse R's random number generator, or simply stick with the system default, the later is consistent with other languages, and is the current behavior.

Java Library
----------------
- [x] Need @yanqingmen to update the java make script.

Handling Pull Request
------------------------------
- PRs with respect to language bindings can be merged into master, while the PRs related to C++ library willl need to be merged into the brick branch
-  We will aim the final merge back in a month.

**Comment by tqchen** [comment]
The https://github.com/dmlc/xgboost/tree/brick branch is tested on both python and R version, to make sure things compile and runs. Here are things we need before the version get merged into master.

For compile with less code deps, https://github.com/dmlc/xgboost/tree/brick/amalgamation can be used, but these can run slower. The C API stays the same for now, so all the language binding code should work directly without modification(other than points to lib/libxgboost.so instead of lib/libxgboostwrapper.so)

General
-----------
- [ ] Reconfigure the travis script to make sure we runs on travis
- [ ] Windows project is outdated, I am thinking of switching to CMake for windows, need a volunteer on this
- [ ] Create a release tag for current master, we can discuss the version number, either 0.5 or 0.45 is fine.

R Library
------------
- [ ] Setup drat release workflow, in https://github.com/dmlc/drat
- [ ] Decide if we want to reuse R's random number generator, or simply stick with the system default, the later is consistent with other languages, and is the current behavior.

Java Library
----------------
- [ ] Need @yanqingmen to update the java make script.

Handling Pull Request
------------------------------
- PRs with respect to language bindings can be merged into master, while the PRs related to C++ library willl need to be merged into the brick branch
-  We will aim the final merge back in a month.

**Comment by tqchen** [comment]
cc @pommedeterresautee @antinucleon @terrytangyuan @hetong007 @yanqingmen 

I will need help from developers and others to make this happen.

**Comment by terrytangyuan** [comment]
@tqchen Could you clarify the difference between two random number generators? But just from what you said, it would be better to be consistent with other bindings. 

I've used drat to install stuff but never uploaded anything to drat before. Is it possible to set up a Travis for drat repo to build R packages automatically on different systems on weekly basis?

**Comment by tqchen** [comment]
Normally R prefers uses its own PRNG so seed can be set via ```set.seed```, there is no other obvious difference.

**Comment by pommedeterresautee** [comment]
@tqchen Regarding Drat, what is expecting to be added/improved?

**Comment by tqchen** [comment]
@pommedeterresautee Mainly figure out an release script to build the R package (and possibly binary dll for windows and mac users) others should remain the same

**Comment by thirdwing** [comment]
Just more info about the C++11 status on Windows. I am one of people working on this in last summer.

(1) The new Rtools 3.3 includes GCC 4.9.3 with posix threading model. It means the full C++11 support and std::thread support. https://github.com/rwinlib/r-base#readme

(2) It hasn't been fully tested. I mean all packages on BioC and CRAN

(3) This is a breaking upgrade for Rtools. The exception model and threading model are changed, and there is no multilib support. The whole building system in CRAN and BioC need to be updated, and this is expected to be done by the end of this year.

(4) The latest Solaris Studio 12.4 has full C++11 support and the CRAN building system will be updated later.

(5) BioC still requires all packages can be compiled using GCC 4.2.1 and I don't think they will change soon.

**Comment by thirdwing** [comment]
More info about R's random number generator.

(1) Theoretically, we should use R's own RNG. This makes the result reproducible when users set the same seed;

(2) only three RNG functions are provided by R (if I remember right):
```
double unif_rand();
double norm_rand();
double exp_rand();
```

**Comment by terrytangyuan** [comment]
Let's stick with R's own RNG then even though it's limited. It's just more of a conventional thing to use it to reproduce results. 

@thirdwing Looks like you are already working on drat for mxnet. Would you be able to take this routinely task for xgboost as well?

**Comment by tqchen** [comment]
I have created a release tag here https://github.com/dmlc/xgboost/releases/tag/0.47 from current master.

This will be checkpoint of current state before we move to the brick version.

**Comment by tqchen** [comment]
@terrytangyuan @hetong007 can you check this r test error https://travis-ci.org/dmlc/xgboost/jobs/102497804#L2942 ?

**Comment by terrytangyuan** [comment]
@tqchen I just ran the previous version and it passed. But it seems like to be off of the expected value by a lot. Have you changed any RNG that relate to this error? The result should always reproducible if the random seed is fixed, at least from previous version it is the case.

**Comment by terrytangyuan** [comment]
If you want to bypass that, change this `tolerance` [here](https://github.com/dmlc/xgboost/blob/master/R-package/tests/testthat/test_poisson_regression.R#L13). I am not very sure why the result is not reproducible though.

**Comment by tqchen** [comment]
Yes,  the PRNG has been changed since brick version.

**Comment by tqchen** [comment]
OK, I relaxed the condition, and clean up the travis to make it more tight, now things pass

**Comment by tqchen** [comment]
The R-package has been updated to fix  the PRNG and the console issue. @hetong007 seems there are a few checks in the R side which we can fix in the future.

**Comment by tqchen** [comment]
I also updated 
https://github.com/tqchen/xgboost/blob/brick/doc/build.md to contain instructions on build on windows and linux. We now support mingw build. which might help some windows users to get rid of msvc

**Comment by tqchen** [comment]
@hetong007 @terrytangyuan I think the R package should be ready to go. Please check the new instruction in https://github.com/dmlc/xgboost/tree/brick/R-package  works on the systems you have. note we need ```install_git```

I would also need you guys to setup the drat repo. @thirdwing can you help on this, or give some advice on how it can be done?

**Comment by terrytangyuan** [comment]
@tqchen Awesome! Yes it's working on my mac.

**Comment by tqchen** [comment]
I added a similar rmarkdown online hosting script as in mxnet https://github.com/dmlc/xgboost/tree/brick/doc/R-package

@pommedeterresautee @hetong007 can you update the links to rmarkdowns(I think we can include another one from otto challenge example). Also please check the original Rmarkdown, which seems to breaks in some usages.

One note on writing rmarkdown(please only use the first level header once in the title, otherwise this will mess up the document lists)

**Comment by tqchen** [comment]
Now everything except the drat workflow finishes, we will merge brick version to master in next week

**Comment by tqchen** [comment]
The new version is now merged into master. I will open new issues for the leftovers
