### ISSUE TITLE
1.5.2 Patch Release.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#7557]
This will be a bug fix release after 1.5.1. Please comment if you think there are commits that should be backported.
@dmlc/xgboost-committer

- [x] https://github.com/dmlc/xgboost/pull/7524
- [x] https://github.com/dmlc/xgboost/pull/7538
- [x] https://github.com/dmlc/xgboost/pull/7541
- [x] https://github.com/dmlc/xgboost/pull/7508
- [x] https://github.com/dmlc/xgboost/pull/7554
- [x] https://github.com/dmlc/xgboost/pull/7360

**Comment by trivialfis** [comment]
# Rhub

```
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(rhub)
> cran_prep <- check_for_cran(path = "./xgboost", email = "jm.yuan@outlook.com")
─  Building package
─  Uploading package
─  Preparing build, see status at
   https://builder.r-hub.io/status/xgboost_1.5.2.1.tar.gz-9112bc028d224e1da29ac136be3bbea9
   https://builder.r-hub.io/status/xgboost_1.5.2.1.tar.gz-2e87775819f94b57aba93592a34045e8
   https://builder.r-hub.io/status/xgboost_1.5.2.1.tar.gz-f8772900cb944214b9f10cf5685ff4d4
   https://builder.r-hub.io/status/xgboost_1.5.2.1.tar.gz-af160c56f6f747cd91b449cdb14bba51
─  Build started
─  Creating new user
─  Downloading and unpacking package file
─  Querying package dependencies
─  Installing package dependencies
─  Running R CMD check
   setting _R_CHECK_FORCE_SUGGESTS_ to false
   setting R_COMPILE_AND_INSTALL_PACKAGES to never
   setting R_REMOTES_STANDALONE to true
   setting R_REMOTES_NO_ERRORS_FROM_WARNINGS to true
   setting _R_CHECK_FORCE_SUGGESTS_ to true
   setting _R_CHECK_CRAN_INCOMING_USE_ASPELL_ to true
   'getOption("repos")' replaces Bioconductor standard repositories, see
   '?repositories' for details
   
   replacement repositories:
       CRAN: https://cloud.r-project.org
   
─  using log directory 'C:/Users/USERkrXzntUWGv/xgboost.Rcheck'
─  using R Under development (unstable) (2021-12-17 r81389 ucrt)
─  using platform: x86_64-w64-mingw32 (64-bit)
─  using session charset: UTF-8 (801ms)
─  using option '--as-cran'
✔  checking for file 'xgboost/DESCRIPTION'
─  checking extension type ... Package
─  this is package 'xgboost' version '1.5.2.1' (805ms)
N  checking CRAN incoming feasibility (18.5s)
   Maintainer: 'Tong He <hetong007@gmail.com>'
   
   Found the following (possibly) invalid URLs:
     URL: https://research.fb.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/ (moved to https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/)
       From: man/xgb.create.features.Rd
       Status: 200
       Message: OK
     URL: https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/ (moved to https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/)
       From: inst/doc/discoverYourData.html
       Status: 200
       Message: OK
   
   The Date field is over a month old.
✔  checking package namespace information
✔  checking package dependencies (800ms)
✔  checking if this is a source package
✔  checking if there is a namespace
✔  checking for executable files (2.4s)
✔  checking for hidden files and directories
✔  checking for portable file names
✔  checking serialization versions
✔  checking whether package 'xgboost' can be installed (2m 42.9s)
✔  checking installed package size
✔  checking package directory
✔  checking for future file timestamps (1.2s)
✔  checking 'build' directory
✔  checking DESCRIPTION meta-information
N  checking top-level files
   Non-standard file/directory found at top level:
     'CMakeLists.txt'
✔  checking for left-over files
✔  checking index information
✔  checking package subdirectories (1.2s)
✔  checking R files for non-ASCII characters
✔  checking R files for syntax errors
✔  checking whether the package can be loaded (1.2s)
✔  checking whether the package can be loaded with stated dependencies (2.5s)
✔  checking whether the package can be unloaded cleanly (1.2s)
✔  checking whether the namespace can be loaded with stated dependencies (1.2s)
✔  checking whether the namespace can be unloaded cleanly (2.5s)
✔  checking loading without being on the library search path (1.3s)
✔  checking use of S3 registration (1.2s)
✔  checking dependencies in R code (3.8s)
✔  checking S3 generic/method consistency (1.4s)
✔  checking replacement functions (1.6s)
✔  checking foreign function calls (2.6s)
✔  checking R code for possible problems (16.7s)
✔  checking Rd files
✔  checking Rd metadata
✔  checking Rd line widths
✔  checking Rd cross-references (1.5s)
✔  checking for missing documentation entries (1.6s)
✔  checking for code/documentation mismatches (6.7s)
✔  checking Rd \usage sections (3.3s)
✔  checking Rd contents
✔  checking for unstated dependencies in examples (1.5s)
✔  checking contents of 'data' directory
✔  checking data for non-ASCII characters (2.7s)
✔  checking data for ASCII and uncompressed saves
✔  checking line endings in shell scripts
✔  checking line endings in C/C++/Fortran sources/headers
✔  checking line endings in Makefiles
✔  checking compilation flags in Makevars (1.5s)
N  checking for GNU extensions in Makefiles
   GNU make is a SystemRequirements.
✔  checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS)
✔  checking use of PKG_*FLAGS in Makefiles
✔  checking use of SHLIB_OPENMP_*FLAGS in Makefiles
✔  checking pragmas in C/C++ headers and code
✔  checking compilation flags used
✔  checking compiled code (48.2s)
N  checking sizes of PDF files under 'inst/doc' (806ms)
   Unable to find GhostScript executable to run checks on size reduction
✔  checking installed files from 'inst/doc'
✔  checking files in 'vignettes'
✔  checking examples (19.4s)
✔  checking for unstated dependencies in 'tests'
─  checking tests
✔  Running 'testthat.R' [76s] (1m 16.1s)
✔  checking for unstated dependencies in vignettes (1m 16.1s)
✔  checking package vignettes in 'inst/doc' (2s)
   Build timed out (after 30 minutes). Marking the build as failed.
   Build was aborted
   Pinging https://builder.r-hub.io/build/FAILURE/xgboost_1.5.2.1.tar.gz-9112bc028d224e1da29ac136be3bbea9/2022-01-16T11:27:03Z
   {"status":"ok"}
   Finished: FAILURE
    
> cran_prep

── xgboost 1.5.2.1: NOTE

  Build ID:   xgboost_1.5.2.1.tar.gz-9112bc028d224e1da29ac136be3bbea9
  Platform:   Windows Server 2022, R-devel, 64 bit
  Submitted:  43m 27.9s ago
  Build time: 43m 9.5s

❯ checking CRAN incoming feasibility ... NOTE
  Maintainer: 'Tong He <hetong007@gmail.com>'
  
  Found the following (possibly) invalid URLs:
    URL: https://research.fb.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/ (moved to https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/)
      From: man/xgb.create.features.Rd
      Status: 200
      Message: OK
    URL: https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/ (moved to https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/)
      From: inst/doc/discoverYourData.html
      Status: 200
      Message: OK
  
  The Date field is over a month old.

❯ checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    'CMakeLists.txt'

❯ checking for GNU extensions in Makefiles ... NOTE
  GNU make is a SystemRequirements.

❯ checking sizes of PDF files under 'inst/doc' ... NOTE
  Unable to find GhostScript executable to run checks on size reduction

0 errors ✔ | 0 warnings ✔ | 4 notes ✖

── xgboost 1.5.2.1: NOTE

  Build ID:   xgboost_1.5.2.1.tar.gz-2e87775819f94b57aba93592a34045e8
  Platform:   Ubuntu Linux 20.04.1 LTS, R-release, GCC
  Submitted:  43m 28s ago
  Build time: 36m 32s

❯ checking CRAN incoming feasibility ... NOTE
  Maintainer: ‘Tong He <hetong007@gmail.com>’
  
  Found the following (possibly) invalid URLs:
    URL: https://research.fb.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/ (moved to https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/)
      From: man/xgb.create.features.Rd
      Status: 200
      Message: OK
    URL: https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/ (moved to https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/)
      From: inst/doc/discoverYourData.html
      Status: 200
      Message: OK
  
  The Date field is over a month old.

❯ checking installed package size ... NOTE
    installed size is 64.7Mb
    sub-directories of 1Mb or more:
      libs  63.8Mb

❯ checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘CMakeLists.txt’

❯ checking for GNU extensions in Makefiles ... NOTE
  GNU make is a SystemRequirements.

❯ checking examples ... NOTE
  Examples with CPU (user + system) or elapsed time > 5s
                 user system elapsed
  xgb.plot.shap 8.138  0.056   2.017

0 errors ✔ | 0 warnings ✔ | 5 notes ✖

── xgboost 1.5.2.1: WARNING

  Build ID:   xgboost_1.5.2.1.tar.gz-f8772900cb944214b9f10cf5685ff4d4
  Platform:   Fedora Linux, R-devel, clang, gfortran
  Submitted:  43m 28s ago
  Build time: 25m 23.3s

❯ checking re-building of vignette outputs ... WARNING
  Error(s) in re-building vignettes:
  --- re-building ‘discoverYourData.Rmd’ using rmarkdown
  Loading required package: xgboost
  Loading required package: Matrix
  Loading required package: data.table
  Loading required package: vcd
  Loading required package: grid
  Warning in chisq.test(df$Age, output_vector) :
    Chi-squared approximation may be incorrect
  Warning in chisq.test(df$AgeDiscret, output_vector) :
    Chi-squared approximation may be incorrect
  Warning in chisq.test(df$AgeCat, output_vector) :
    Chi-squared approximation may be incorrect
  --- finished re-building ‘discoverYourData.Rmd’
  
  --- re-building ‘xgboostPresentation.Rmd’ using rmarkdown
  --- finished re-building ‘xgboostPresentation.Rmd’
  
  --- re-building ‘xgboostfromJSON.Rmd’ using rmarkdown
  --- finished re-building ‘xgboostfromJSON.Rmd’
  
  --- re-building ‘xgboost.Rnw’ using knitr
  Loading required package: knitr
  Error: processing vignette 'xgboost.Rnw' failed with diagnostics:
  Running 'texi2dvi' on 'xgboost.tex' failed.
  LaTeX errors:
  ! LaTeX Error: File `framed.sty' not found.
  
  Type X to quit or <RETURN> to proceed,
  or enter new name. (Default extension: sty)
  
  ! Emergency stop.
  <read *> 
           
  l.30 \makeatletter
                    ^^M
  !  ==> Fatal error occurred, no output PDF file produced!
  --- failed re-building ‘xgboost.Rnw’
  
  SUMMARY: processing the following file failed:
    ‘xgboost.Rnw’
  
  Error: Vignette re-building failed.
  Execution halted

❯ checking CRAN incoming feasibility ... NOTE
  Maintainer: ‘Tong He <hetong007@gmail.com>’
  
  Found the following (possibly) invalid URLs:
    URL: https://research.fb.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/ (moved to https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/)
      From: man/xgb.create.features.Rd
      Status: 200
      Message: OK
    URL: https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/ (moved to https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/)
      From: inst/doc/discoverYourData.html
      Status: 200
      Message: OK
  
  The Date field is over a month old.

❯ checking installed package size ... NOTE
    installed size is 38.7Mb
    sub-directories of 1Mb or more:
      libs  37.8Mb

❯ checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘CMakeLists.txt’

❯ checking for GNU extensions in Makefiles ... NOTE
  GNU make is a SystemRequirements.

❯ checking examples ... NOTE
  Examples with CPU (user + system) or elapsed time > 5s
                     user system elapsed
  xgb.plot.shap     7.807  0.220   2.171
  xgb.plot.deepness 6.141  0.137   2.182

0 errors ✔ | 1 warning ✖ | 5 notes ✖

── xgboost 1.5.2.1: IN-PROGRESS

  Build ID:   xgboost_1.5.2.1.tar.gz-af160c56f6f747cd91b449cdb14bba51
  Platform:   Debian Linux, R-devel, GCC ASAN/UBSAN
  Submitted:  43m 28s ago
```

**Comment by trivialfis** [comment]
I have uploaded the Python packages.

Friendly ping. ;-)
@hetong007 Could you please help with the R package?  I ran cran tests on rhub.  But win builder hasn't responded to me yet for some reason.

@hcho3 Could you please help with maven packages?

**Comment by trivialfis** [comment]
Thank you!

**Comment by hcho3** [comment]
@trivialfis Done.

**Comment by hetong007** [comment]
Thanks for managing this @trivialfis  ! 

The 'invalid URLs' issue can be fixed directly by using the new move-to address. The error in vignette build should be fine for the official CRAN check environment.

Since the maintainer has been changed, you could go ahead and directly submit it at https://cran.r-project.org/submit.html :D

**Comment by trivialfis** [comment]
@hetong007 The maintainer is only changed for testing, I did not include that into the repository here.

I'm happy to start maintaining the R package, however, R is not my day-to-day language, would be great to have you oversee the release process.

**Comment by trivialfis** [comment]
I will try to submit the package tomorrow.

**Comment by hetong007** [comment]
Sorry I'm busy with ICML deadline this week and was absent in this thread. It would be great that you could try to submit the package! On the other hand, I can also take care of it this weekend (after the deadline).

**Comment by trivialfis** [comment]
@hetong007 I have submitted the package and need confirmation from you due to the changed maintainer.  Could you please check your inbox when you are available?  Thank you!

**Comment by hetong007** [comment]
I have just replied. Good luck with the submission!

**Comment by trivialfis** [comment]
Closing this now, will continue to monitor https://cran.r-project.org/web/checks/check_results_xgboost.html .

@hetong007 Thank you for the support!
