### ISSUE TITLE
1.6.1 Patch Release

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#7841]
We have a number of note-worthy fixes in JVM packages and categorical data support, including a fix for `DeviceQuantileDMatrix` in distributed environments, and support for barrier execution mode in the spark package to prevent potential hang during training.

- [ ] https://github.com/dmlc/xgboost/pull/7823
- [ ] https://github.com/dmlc/xgboost/pull/7834
- [ ] https://github.com/dmlc/xgboost/pull/7836
- [ ] https://github.com/dmlc/xgboost/pull/7840
- [ ] https://github.com/dmlc/xgboost/pull/7845
- [ ] https://github.com/dmlc/xgboost/pull/7846
- [ ] https://github.com/dmlc/xgboost/pull/7844

cc @wbo4958

**Comment by wbo4958** [comment]
@trivialfis Please also add https://github.com/dmlc/xgboost/pull/7845

**Comment by wbo4958** [comment]
@trivialfis Please also add https://github.com/dmlc/xgboost/pull/7846

**Comment by trivialfis** [comment]
Will make a patch release for Python as well for fixes in categorical data support.

**Comment by trivialfis** [comment]
@hcho3 I will submit the patch release for Python today. Could you please help with the JVM packages when you are available?

**Comment by trivialfis** [comment]
All Python packages are submitted.

**Comment by hcho3** [comment]
@trivialfis I'm submitting the JVM package today.
