### ISSUE TITLE
1.6.2 patch release

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#8155]
We have a couple of fixes in the master branch that is not yet available in a public release yet. Following is a list of commits/PRs that are pending for being backported. If you have some other commits in mind please let me know in the comments.

* To be backported

- [x] 8ba4722d0 * Remove pyarrow workaround. (#7884)
- [x] db80671d6 * Fix monotone constraint with tuple input. (#7891)
- [x] d314680a1 * Verify shared object version at load. (#7928)
- [x] 8f8bd8147 * Fix LTR with weighted Quantile DMatrix. (#7975)
- [x] dcaf58047 * Fix Python package source install. (#8036)
- [ ] 579ab23b1 * Check cudf lazily (#8084)
- [x] 5156be0f4 * Limit `max_depth` to 30 for GPU. (#8098)
- [x] 2cba1d9fc * Fix compatibility with latest cupy. (#8129)
- [x] https://github.com/dmlc/xgboost/pull/8018
- [x] https://github.com/dmlc/xgboost/pull/8149

* Optional

These are optional and will be backported if it blocks the CI.

- [ ] d285d6ba2 * Reduce regularization in GPU gblinear test. (#8010)
- [ ] 4a87ea49b * Reduce regularization for CPU gblinear. (#8013)
- [ ] f24bfc768 * Bump R cache version. (#8044)
- [ ] a5bc8e2c6 * Fix mypy error with the latest dask. (#8052)
- [x] 895962283 * [dask] Use an invalid port for test. (#8064)
- [ ] 36cf979b8 * [CI] Fix S3 uploads (#8069)
- [ ] 0ce80b7bc * Mitigate flaky GPU test. (#8078)
- [x] e44a08262 * [jvm-packages] update nccl version to 2.12.12-1 (#8015)
- [x] bcc8679a0 * Update CUDA docker image and NCCL. (#8139) (need jvm)

**Comment by natmod** [comment]
Can you add https://github.com/dmlc/xgboost/pull/8149?

**Comment by trivialfis** [comment]
@natmod Thanks, will backport it as well.

**Comment by trivialfis** [comment]
Will make the Python release once all backports are merged. (likely tomorrow).

**Comment by trivialfis** [comment]
Python packages are uploaded to pypi @hcho3 Would you like to help upload the jvm packages?

**Comment by hcho3** [comment]
@trivialfis The JVM packages are now up.

**Comment by trivialfis** [comment]
Great. I will close the issue now since there's no fix for cran package.

**Comment by grafail** [comment]
Are there any estimates perhaps for #8084?
