### ISSUE TITLE
1.7.0 Release Candidate

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#8366]
We are about to release version 1.7.0 of XGBoost. In the next week, we invite everyone to try out the release candidate (RC).

Roadmap: https://github.com/dmlc/xgboost/issues/8282
Release note: https://github.com/dmlc/xgboost/pull/8374

Feedback period: until the end of October 30, 2022. No new feature will be added to the release; only critical bug fixes will be backported.

@dmlc/xgboost-committer

### Available packages:

- **Python packages**:
```
pip install xgboost==1.7.0rc1
```
- **R packages**:

R binary packages with CUDA enabled for testing:

Linux x86_64: [Download](https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/release_1.7.0/xgboost_r_gpu_linux_463313d9be3a0aa6da65da852cfb2c1e2a026cd2.tar.gz)
Windows x86_64: [Download](https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/release_1.7.0/xgboost_r_gpu_win64_463313d9be3a0aa6da65da852cfb2c1e2a026cd2.tar.gz)

sha256sum:
```
ebaa8517b673735ae87b3b27d2f744b77d61974d4411c161455eefd1cf59cc39  xgboost_r_gpu_linux_1.7.0-rc1.tar.gz
75f678ea669a82459f506c3c0cc613b5e8fa20a6898b4d883e6cf846f1a39c16  xgboost_r_gpu_win64_1.7.0-rc1.tar.gz
```
Install:
``` bash
R CMD INSTALL ./xgboost_r_gpu_linux.tar.gz
```

- **JVM packages**
<details><summary>Show instructions (Maven/SBT)</summary>
<p>

Maven
```xml
<dependencies>
  ...
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j_2.12</artifactId>
      <version>1.7.0-RC1</version>
  </dependency>
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-spark_2.12</artifactId>
      <version>1.7.0-RC1</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>XGBoost4J Release Repo</id>
    <name>XGBoost4J Release Repo</name>
    <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/</url>
  </repository>
</repositories>
```

SBT
```scala
libraryDependencies ++= Seq(
  "ml.dmlc" %% "xgboost4j" % "1.7.0-RC1",
  "ml.dmlc" %% "xgboost4j-spark" % "1.7.0-RC1"
)
resolvers += ("XGBoost4J Release Repo"
              at "https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/")
```
</p>
</details>

Starting from 1.2.0, XGBoost4J-Spark supports training with NVIDIA GPUs. To enable this capability, download artifacts suffixed with `-gpu`, as follows:

<details><summary>Show instructions (Maven/SBT)</summary>
<p>

Maven
```xml
<dependencies>
  ...
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-gpu_2.12</artifactId>
      <version>1.7.0-RC1</version>
  </dependency>
  <dependency>
      <groupId>ml.dmlc</groupId>
      <artifactId>xgboost4j-spark-gpu_2.12</artifactId>
      <version>1.7.0-RC1</version>
  </dependency>
</dependencies>

<repositories>
  <repository>
    <id>XGBoost4J Release Repo</id>
    <name>XGBoost4J Release Repo</name>
    <url>https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/</url>
  </repository>
</repositories>
```

SBT
```scala
libraryDependencies ++= Seq(
  "ml.dmlc" %% "xgboost4j-gpu" % "1.7.0-RC1",
  "ml.dmlc" %% "xgboost4j-spark-gpu" % "1.7.0-RC1"
)
resolvers += ("XGBoost4J Release Repo"
              at "https://s3-us-west-2.amazonaws.com/xgboost-maven-repo/release/")
```
</p>
</details>

### PRs to be backported
- [x] https://github.com/dmlc/xgboost/pull/8369
- [x] https://github.com/dmlc/xgboost/pull/8378
- [x] https://github.com/dmlc/xgboost/pull/8380
- [x] https://github.com/dmlc/xgboost/pull/8385
- [x] https://github.com/dmlc/xgboost/pull/8384

**Comment by trivialfis** [comment]
All packages are uploaded.

**Comment by hcho3** [comment]
The 1.7.0 stable version is now available on PyPI.

**Comment by trivialfis** [comment]
Will upload R package to CRAN as well.

**Comment by trivialfis** [comment]
Submitted R package to cran, let's track https://cran.r-project.org/web/checks/check_results_xgboost.html .

**Comment by trivialfis** [comment]
@hcho3 Could you please help make the jvm release when you are available?

**Comment by trivialfis** [comment]
pre-tests failed with following notes:

```

Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: compilation flags in Makevars, Result: NOTE
  Package has both 'src/Makevars.in' and 'src/Makevars'.
  Installation with --no-configure' is unlikely to work.  If you intended
  'src/Makevars' to be used on Windows, rename it to 'src/Makevars.win'
  otherwise remove it.  If 'configure' created 'src/Makevars', you need a
  'cleanup' script.

Flavor: r-devel-linux-x86_64-debian-gcc
Check: examples, Result: NOTE
  Examples with CPU time > 2.5 times elapsed time
                       user system elapsed ratio
  cb.gblinear.history 1.454  0.017    0.49 3.002
```

Need to cleanup the automake files, not sure what to do with the CPU time.

**Comment by trivialfis** [comment]
Posted a question on the r devel list about the CPU time.

**Comment by trivialfis** [comment]
Running tests on winbuilder for CRAN submission again.

**Comment by hcho3** [comment]
JVM packages have been available on Maven Central since Nov 4

**Comment by trivialfis** [comment]
I made another attempt for R package today, still failing for the same error with `cb.gblinear.history` even after reducing the number of threads to 1. I haven't been able to figure out the exact cause.

**Comment by trivialfis** [comment]
@hcho3 @hetong007 @RAMitchell We might skip 1.7 for CRAN due to non-trivial changes required to pass the CRAN tests. At the moment, we are running into the error https://github.com/dmlc/xgboost/issues/8366#issuecomment-1304096969 . I haven't been able to figure out the exact cause since I can't reproduce it on my devices (tried both 16 cores and 12 cores machines).
Also, there are known issues like https://github.com/dmlc/xgboost/pull/8455

**Comment by trivialfis** [comment]
I made another submission. Fingers crossed.

**Comment by hcho3** [comment]
@trivialfis We got another warning:
```
Found the following significant warnings:
  src/predictor/cpu_predictor.cc:167:27: warning: narrowing conversion of '(long long unsigned int)beg' from 'long long unsigned int' to 'size_t' {aka 'unsigned int'} inside { } [-Wnarrowing]
See https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/xgboost-00install.html for details.
```
https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/xgboost-00check.html

Should we consider setting up CI for 32-bit envs?

**Comment by trivialfis** [comment]
@hcho3 I don't think we will maintain a 32-bit package, its tests are failing anyway. Unless there's another message from the cran maintainer we might just leave it unsupported.

**Comment by hcho3** [comment]
All we have to do is to ensure that the code builds without warning using 32-bit system. We've already disabled all tests for 32-bit.

**Comment by trivialfis** [comment]
there's an error in examples, you can search "ERROR" in the link you shared.

**Comment by hcho3** [comment]
Let's go ahead and disable all tests for 32-bit

**Comment by trivialfis** [comment]
@hcho3 

> Should we consider setting up CI for 32-bit envs?

Would you like to help with this? Maybe an optional test like R nold?

**Comment by hcho3** [comment]
Sure, I'll do it

**Comment by trivialfis** [comment]
Thank you! I will come back to this tomorrow.
