### ISSUE TITLE
1.7.4 Patch Release.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#8803]
This is a bug-fix release for 1.7.

- [x] https://github.com/dmlc/xgboost/pull/8684
- [x] https://github.com/dmlc/xgboost/pull/8690
- [x] https://github.com/dmlc/xgboost/pull/8754
- [x] https://github.com/dmlc/xgboost/pull/8749
- [x] https://github.com/dmlc/xgboost/pull/8772
- [x] https://github.com/dmlc/xgboost/pull/8762
- [x] https://github.com/dmlc/xgboost/pull/8809

**Comment by trivialfis** [comment]
R winbuilder result. It's failing on i386 but otherwise looks good.
```
Your package xgboost_1.7.4.1.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/GyaSK35w21NB
The files will be removed after roughly 72 hours.
Installation time in seconds: 703
Check time in seconds: 432
Status: OK
R version 4.2.2 (2022-10-31 ucrt)
```

```
Your package xgboost_1.7.4.1.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/TmDkKJPbkQ9G
The files will be removed after roughly 72 hours.
Installation time in seconds: 1412
Check time in seconds: 557
Status: 2 ERRORs, 1 WARNING, 1 NOTE
R version 4.1.3 (2022-03-10)
```

**Comment by trivialfis** [comment]
Failed on CRAN pre-test:
```
* checking C++ specification ... NOTE
  Specified C++14: please drop specification unless essential
```

**Comment by hcho3** [comment]
Let me upload the JVM packages

**Comment by trivialfis** [comment]
@hcho3 If you haven't, please don't upload anything yet.

**Comment by hcho3** [comment]
@trivialfis Is there any more modifications to make?

**Comment by trivialfis** [comment]
We might need a fix for https://github.com/dmlc/xgboost/issues/8824 , @RAMitchell might be able to share some insights when he's available.

I'm looking into https://github.com/dmlc/xgboost/pull/8816 , which is not reproducible on my machines (tried two different devices and docker). Based on the log from this debug PR, the thread local cache might be problematic even though I don't have any clue about it. The regression test is accessing a DMatrix constructed from a classification test ...

**Comment by trivialfis** [comment]
Let's skip https://github.com/dmlc/xgboost/pull/8816 for now. It's caused by scaling using a gc thread for booster destruction, resulting in different threads for construction and destruction.

**Comment by marcphilipp** [comment]
Any updates on getting the JVM packages to Maven Central?

**Comment by trivialfis** [comment]
@hcho3 Please continue the 1.7.4 release. I will wrap up all needed changes for 2.0 as soon as possible. The 1.7.4 release branch is quite difficult to work with now with the CI upgraded on the master branch.

**Comment by hcho3** [comment]
I went ahead and uploaded 1.7.3 to Maven Central. https://repo1.maven.org/maven2/ml/dmlc/xgboost4j_2.12/1.7.4/
