### ISSUE TITLE
JVM(Java,Scala) Package Progress

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#884]
This is an issue tracking more clean integration with JVM Stack and try to improve what we current have in xgboost4j.

Major Goals
----------------
- [x] Support both Java and Scala API
- [x] Support distributed version with the JVM package.
- [x] Integration with existing JVM distributed computing stacks.

Things to Discuss and TODO
---------------------------------------
How to organize the code(JNI, scala, java) code as we move forward, where to put documents.

Maybe we will have a folder called jvm-package, which contains JNI, scala and java implementations of current API.

People
---------
@CodingCat is discussing the possibility of spark integration with me and we think it should be possible after the scala package is done, so I will let him lead the discussion and coordination of this issue.

I am also calling other contributors who might be expert to participate the discussion, and let us make something interesting happen

**Comment by tqchen** [comment]
also cc @terrytangyuan @javelinjs  who are working on mxnet-scala package as well as original creator @yanqingmen

**Comment by terrytangyuan** [comment]
Good idea. Not super familiar but would definitely love to join the discussion and learn from experts. So is he working on the Scala package already? If so, where can I track progress?

**Comment by CodingCat** [comment]
Hi,@terrytangyuan 

I'm just start the job, will post a design doc in very soon

**Comment by javelinjs** [comment]
I suggest to write the functional codes in scala and provide java-friendly APIs, as Spark does. You can refer to https://github.com/javelinjs/mxnet/tree/scala-package-l/scala-package for JNI code organization. Also JNA (https://github.com/java-native-access/jna) is a good choice for simplifying JNI implementation, if you like.

Also cc my colleague @wenmin-wu who may be interested in this issue and have some ideas on how to design the JVM APIs.

**Comment by tqchen** [comment]
Just to clarify, there is already a JNI java API here https://github.com/dmlc/xgboost/tree/master/java, so this is more about refactoring and making the package cleaner and general

**Comment by CodingCat** [comment]
@javelinjs thanks for the suggestions. I was also looking at the possibility to provide functional API in scala

The most barrier here is from the current native APIs. The current native APIs in xgboost is essentially imperative (e.g. modifying the pointer which is passed as the parameter)....this matter makes writing the core part in a functional style pretty hard...and at the same time, as @tqchen mentioned, we have some existing JNI (and imperative) APIs there,  we do not want to discard them entirely.

The basic idea in my head is 1) separate the existing JNI interaction part is `common` package/module, which is not exposed to the user  2) provide Java APIs and Scala APIs; 3) Java/Scala APIs calls common module to call native methods; 4) if possible, Scala APIs shall wrap the core part and provide a functional interface...

**Comment by CodingCat** [comment]
I created a WIP PR in https://github.com/dmlc/xgboost/pull/890

**Comment by tqchen** [comment]
The JVM Package is now ready for beta testing, see pointer here https://github.com/dmlc/xgboost/tree/master/jvm-packages

We need more efforts on testing documentation and tutorials

**Comment by tqchen** [comment]
close and move to https://github.com/dmlc/xgboost/issues/884

**Comment by CodingCat** [comment]
I think we can close this one?
