### ISSUE TITLE
1.7.5 Patch Release. 

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#8996]
This is a bug-fix release for 1.7.

- [x] https://github.com/dmlc/xgboost/pull/8991
- [x] https://github.com/dmlc/xgboost/pull/8692
- [x] https://github.com/dmlc/xgboost/pull/8855
- [x] https://github.com/dmlc/xgboost/pull/8860
- [x] https://github.com/dmlc/xgboost/pull/8850
- [x] https://github.com/dmlc/xgboost/pull/8853
- [x] https://github.com/dmlc/xgboost/pull/8997
- [x] https://github.com/dmlc/xgboost/pull/8998

**Comment by trivialfis** [comment]
Hi @hcho3 , I have submitted the update to both pypi and [cran](https://cran.r-project.org/web/packages/xgboost/index.html) (which is still being tested). Could you please help make the maven release when you are available?

**Comment by hcho3** [comment]
The JVM packages are now up.

**Comment by trivialfis** [comment]
Thank you for making the jvm release!
