### ISSUE TITLE
1.7.6 Patch Release

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#9275]
This is a bug-fix release for 1.7.

- [x] https://github.com/dmlc/xgboost/pull/9272
- [x] https://github.com/dmlc/xgboost/pull/9122
- [x] https://github.com/dmlc/xgboost/pull/9106
- [x] https://github.com/dmlc/xgboost/pull/9014
- [x] https://github.com/dmlc/xgboost/pull/9022
- [x] https://github.com/dmlc/xgboost/pull/8959
- [x] https://github.com/dmlc/xgboost/pull/9096

cc @hcho3 @WeichenXu123

**Comment by hcho3** [comment]
Can we also backport https://github.com/dmlc/xgboost/pull/8959 so that the stable version doc works properly? Currently, the search is broken in the stable version doc.

**Comment by trivialfis** [comment]
Got it.

**Comment by trivialfis** [comment]
Will bump the version tomorrow. I was trying to support empty partition in prediction, bit seems unnecessary now, a better error message can be made for 2.0

**Comment by hcho3** [comment]
@trivialfis Should I publish a new JVM package to Maven Central?

**Comment by trivialfis** [comment]
@hcho3 Yes please. I will submit the CRAN package tomorrow as well.

**Comment by trivialfis** [comment]
I think there are changes on the CRAN with updates on the core R, new warnings after 1.7.5:
```
* checking S3 generic/method consistency ... NOTE
Mismatches for apparent methods not registered:
format:
  function(x, ...)
format.eval.string:
  function(iter, eval_res, eval_err)
See section ‘Registering S3 methods’ in the ‘Writing R Extensions’
manual.
```
```
Examples with CPU (user + system) or elapsed time > 5s
                   user system elapsed
xgb.plot.deepness 9.553  0.212   1.253
xgb.plot.shap     7.625  0.158   1.128
Examples with CPU time > 2.5 times elapsed time
                      user system elapsed  ratio
xgb.model.dt.tree    2.244  0.089   0.073 31.959
xgb.config           1.427  0.058   0.047 31.596
xgb.DMatrix          1.120  0.048   0.037 31.568
xgb.serialize        1.038  0.026   0.047 22.638
xgb.train            1.208  0.041   0.123 10.154
xgb.plot.multi.trees 3.389  0.149   0.370  9.562
xgb.plot.deepness    9.553  0.212   1.253  7.793
xgb.plot.shap        7.625  0.158   1.128  6.900
xgb.plot.importance  1.335  0.076   0.377  3.743
```

I won't be able to fix them in time for 1.7.6. I will skip this version for CRAN and focus on 2.0 instead.

**Comment by trivialfis** [comment]
@hcho3 Feel free to close the issue once the maven package is published.

**Comment by hcho3** [comment]
XGBoost 1.7.6 is now available on Maven Central.
